on: push
name: Hexo Build Test
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Clean
      uses: heowc/action-hexo@master
      with:
        args: clean
    - name: Generate
      uses: heowc/action-hexo@master
      with:
        args: generate
